command: [
  "python",
  "app.py"
]
env:
- name: "DATABRICKS_WAREHOUSE_ID"
  valueFrom: "sql_warehouse"
- name: "DATABRICKS_ENDPOINT"
  valueFrom: "serving_endpoint"
- name: "SERVING_PAT"
  valueFrom: "secret"  
